name = "filcdn-service-monitor"
main = "bin/service-monitor.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
logpush = true

[observability]
enabled = true
head_sampling_rate = 1


[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"
RPC_URL = "https://api.calibration.node.glif.io/"
FILECOIN_WARM_STORAGE_SERVICE_ADDRESS = "0xD9df508aC49161e1E0A8382a3c833728b89bED8C" # TODO

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf101"

[env.calibration.vars]
ENVIRONMENT = "calibration"
RPC_URL = "https://api.calibration.node.glif.io/"
FILECOIN_WARM_STORAGE_SERVICE_ADDRESS = "0xD9df508aC49161e1E0A8382a3c833728b89bED8C" # TODO

[[env.calibration.d1_databases]]
binding = "DB"
database_name = "filcdn-calibration-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf103"

[env.calibration.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[env.mainnet.vars]
ENVIRONMENT = "mainnet"
RPC_URL = "https://api.node.glif.io/"
FILECOIN_WARM_STORAGE_SERVICE_ADDRESS = "0xD9df508aC49161e1E0A8382a3c833728b89bED8C" # TODO

[[env.mainnet.d1_databases]]
binding = "DB"
database_name = "filcdn-mainnet-db"
database_id = "e8de6418-2cb7-4413-9ba0-a9c8aacf9a66"

[env.mainnet.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[[env.dev.queues.producers]]
queue = "transaction-queue"
binding = "TRANSACTION_QUEUE"

[[env.dev.queues.consumers]]
queue = "transaction-queue"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "transaction-dlq"

[[env.mainnet.queues.producers]]
queue = "transaction-queue"
binding = "TRANSACTION_QUEUE"

[[env.mainnet.queues.consumers]]
queue = "transaction-queue"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "transaction-dlq"

[[env.calibration.queues.producers]]
queue = "transaction-queue"
binding = "TRANSACTION_QUEUE"

[[env.calibration.queues.consumers]]
queue = "transaction-queue"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "transaction-dlq"

[[env.dev.workflows]]
name = "transaction-monitor-workflow"
binding = "TRANSACTION_MONITOR_WORKFLOW"
class_name = "TransactionMonitorWorkflow"

[[env.calibration.workflows]]
name = "transaction-monitor-workflow"
binding = "TRANSACTION_MONITOR_WORKFLOW"
class_name = "TransactionMonitorWorkflow"

[[env.mainnet.workflows]]
name = "transaction-monitor-workflow"
binding = "TRANSACTION_MONITOR_WORKFLOW"
class_name = "TransactionMonitorWorkflow"
