name = "filcdn-bad-bits"
main = "bin/scheduler.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
logpush = true

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "BAD_BITS_KV"
id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"

[[env.dev.kv_namespaces]]
binding = "BAD_BITS_KV"
id = "2f2e5486ea0c48e993f6dff87a4aa102"

[[env.dev.r2_buckets]]
binding = "BAD_BITS_R2"
bucket_name = "filbeam-bad-bits-dev"

[env.calibration.vars]
ENVIRONMENT = "calibration"

[[env.calibration.kv_namespaces]]
binding = "BAD_BIT_KV"
id = "178592ee0a3b4b00894a23186b3a0179"

[[env.calibration.r2_buckets]]
binding = "BAD_BITS_R2"
bucket_name = "filbeam-bad-bits-calibration"

[env.calibration.triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes

[env.mainnet.vars]
ENVIRONMENT = "mainnet"

[[env.mainnet.kv_namespaces]]
binding = "BAD_BITS_KV"
id = "7b03c39d53a041fdbe973c20285e16e9"

[[env.mainnet.r2_buckets]]
binding = "BAD_BITS_R2"
bucket_name = "filbeam-bad-bits-mainnet"

[env.mainnet.triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes
