name = "filcdn-bad-bits"
main = "bin/scheduler.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
logpush = true

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "KV"
id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"

[[env.dev.kv_namespaces]]
binding = "KV"
id = "cc15f5038fe140b99af6eebfbcc583f2"

[env.calibration.vars]
ENVIRONMENT = "calibration"

[[env.calibration.kv_namespaces]]
binding = "KV"
id = "19567b7ea80e4a06a0b0db96e525f624"

[env.calibration.triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes

[env.mainnet.vars]
ENVIRONMENT = "mainnet"

[[env.mainnet.kv_namespaces]]
binding = "KV"
id = "6b07420fe34b4f9e87c707f61545ec8b"

[env.mainnet.triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes
