name = "address-checker"
main = "./bin/address-checker.js"
compatibility_date = "2023-10-30"

[triggers]
crons = ["0 0 * * *"] # Run once per day at midnight UTC

[env.dev.vars]
# This dummy key is only used for local development and testing
# For production, the secret is stored in Cloudflare
CHAINALYSIS_API_KEY = "dummy-api-key-for-development-only"

[[d1_databases]]
binding = "DB"
database_name = "filcdn"
database_id = "development-db-id"

[env.dev]
name = "address-checker-dev"
[[env.dev.d1_databases]]
binding = "DB"
database_name = "filcdn-dev"
database_id = "development-db-id"

[env.calibration]
name = "address-checker-calibration"

[[env.calibration.d1_databases]]
binding = "DB"
database_name = "filcdn-calibration"
database_id = "calibration-db-id"