name = "filcdn-indexer"
main = "bin/indexer.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
logpush = true

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"
WALLET_SCREENING_BATCH_SIZE = 1
WALLET_SCREENING_STALE_THRESHOLD_MS = 86400000 # one day
GOLDSKY_SUBGRAPH_URL="https://api.goldsky.com/api/public/project_cmb91qc80slyu01wca6e2eupl/subgraphs/fwss-alpha-calibnet/1.0.0/gn"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf101"

[env.calibration.vars]
ENVIRONMENT = "calibration"
WALLET_SCREENING_BATCH_SIZE = 1
WALLET_SCREENING_STALE_THRESHOLD_MS = 86400000 # one day
GOLDSKY_SUBGRAPH_URL="https://api.goldsky.com/api/public/project_cmb91qc80slyu01wca6e2eupl/subgraphs/fwss-alpha-calibnet/1.0.0/gn"

[[env.calibration.d1_databases]]
binding = "DB"
database_name = "filcdn-calibration-db"
database_id = "78f15bbb-391f-4797-9016-a6cb86c0b9b8"

[env.calibration.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[[env.calibration.queues.producers]]
queue = "indexer-retry-queue-calibration"
binding = "RETRY_QUEUE"

[[env.calibration.queues.consumers]]
queue = "retry-queue"
max_batch_size = 100
max_batch_timeout = 30

[env.mainnet.vars]
ENVIRONMENT = "mainnet"
WALLET_SCREENING_BATCH_SIZE = 10
WALLET_SCREENING_STALE_THRESHOLD_MS = 21600000 # 6 hours
# TODO: Update mainnet goldsky subgraph url
GOLDSKY_SUBGRAPH_URL=""

[[env.mainnet.d1_databases]]
binding = "DB"
database_name = "filcdn-mainnet-db"
database_id = "e8de6418-2cb7-4413-9ba0-a9c8aacf9a66"

[env.mainnet.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[[env.mainnet.queues.producers]]
queue = "retry-queue"
binding = "RETRY_QUEUE"

[[env.mainnet.queues.consumers]]
queue = "retry-queue"
max_batch_size = 100
max_batch_timeout = 30
