name = "filcdn-indexer"
main = "bin/indexer.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
logpush = true

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"
WALLET_SCREENING_BATCH_SIZE = 1
WALLET_SCREENING_STALE_THRESHOLD_MS = 86400000 # one day

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf101"

[env.calibration.vars]
ENVIRONMENT = "calibration"
WALLET_SCREENING_BATCH_SIZE = 1
WALLET_SCREENING_STALE_THRESHOLD_MS = 86400000 # one day

[[env.calibration.d1_databases]]
binding = "DB"
database_name = "filcdn-calibration-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf103"

[env.calibration.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[env.mainnet.vars]
ENVIRONMENT = "mainnet"
WALLET_SCREENING_BATCH_SIZE = 10
WALLET_SCREENING_STALE_THRESHOLD_MS = 21600000 # 6 hours

[[env.mainnet.d1_databases]]
binding = "DB"
database_name = "filcdn-mainnet-db"
database_id = "e8de6418-2cb7-4413-9ba0-a9c8aacf9a66"

[env.mainnet.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[[env.dev.queues.producers]]
queue = "retry-queue-dev"
binding = "RETRY_QUEUE"

[[env.dev.queues.consumers]]
queue = "retry-queue-dev"
max_batch_size = 100
max_batch_timeout = 30

[[env.calibration.queues.producers]]
queue = "retry-queue-calibration"
binding = "RETRY_QUEUE"

[[env.calibration.queues.consumers]]
queue = "retry-queue-calibration"
max_batch_size = 100
max_batch_timeout = 30

[[env.mainnet.queues.producers]]
queue = "retry-queue-mainnet"
binding = "RETRY_QUEUE"

[[env.mainnet.queues.consumers]]
queue = "retry-queue-mainnet"
max_batch_size = 100
max_batch_timeout = 30

