name = "filcdn-retriever"
main = "bin/retriever.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"
CACHE_TTL = 86400
DNS_ROOT = ".localhost"
SERVICE_NAME = "filcdn-retriever"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf101"

[env.calibration .vars]
ENVIRONMENT = "calibration "
CACHE_TTL = 86400
DNS_ROOT = ".calibration.filcdn.io"
SERVICE_NAME = "filcdn-retriever"

[[env.calibration .d1_databases]]
binding = "DB"
database_name = "filcdn-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf103"
