name = "filcdn-retriever"
main = "bin/retriever.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
logpush = true

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"
REQUEST_CACHE_TTL = 86400
BROWSER_CACHE_TTL = 31536000 
DNS_ROOT = ".localhost"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf101"

[env.calibration.vars]
ENVIRONMENT = "calibration "
REQUEST_CACHE_TTL = 86400
BROWSER_CACHE_TTL = 31536000 
DNS_ROOT = ".calibration.filcdn.io"

[[env.calibration.d1_databases]]
binding = "DB"
database_name = "filcdn-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf103"

[env.mainnet.vars]
ENVIRONMENT = "mainnet"
REQUEST_CACHE_TTL = 86400
BROWSER_CACHE_TTL = 31536000 
DNS_ROOT = ".filcdn.io"

[[env.mainnet.d1_databases]]
binding = "DB"
database_name = "filcdn-mainnet-db"
database_id = "e8de6418-2cb7-4413-9ba0-a9c8aacf9a66"
