name: CI
on:
  push:
    branches:
      - main
      - 'update/m2.5'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci

      - run: npm run lint
      - run: npm test

  test-subgraph:
    strategy:
      matrix:
        network: [calibnet, mainnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: subgraph
        run: npm ci

      - name: Select network
        working-directory: subgraph
        run: npm run select-${{ matrix.network }}

      - name: Run codegen
        working-directory: subgraph
        run: npm run codegen

      - name: Test Subgraph
        working-directory: subgraph
        run: npm run test

  deploy:
    strategy:
      matrix:
        environment: [calibration, mainnet]
    if: github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Deploy Piece Retriever and Migrate Database
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: piece-retriever
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: ../db/deploy-${{ matrix.environment }}.sh
          environment: ${{ matrix.environment }}
      - name: Deploy Indexer
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: indexer
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: ${{ matrix.environment }}
      - name: Deploy Bad Bits Updater
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: bad-bits
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: ${{ matrix.environment }}
      - name: Deploy Terminator
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: terminator
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: ${{ matrix.environment }}
      - if: failure()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "alerts",
              "text": "Deployment of `${{ github.event.repository.name }}` to `${{ matrix.environment }}` failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Deployment of `${{ github.event.repository.name }}` to `${{ matrix.environment }}` failed>*"
                  }
                }
              ]
            }
